#!/bin/sh /etc/rc.common
# FM350-GL Manager Init Script
# OpenWrt procd service

USE_PROCD=1

START=95
STOP=10

PROG=/usr/sbin/fm350-manager
PIDFILE=/var/run/fm350-manager.pid

start_service() {
  procd_open_instance
  
  procd_set_param command "$PROG"
  procd_set_param pidfile "$PIDFILE"
  
  procd_set_param respawn 3600 5 0
  
  procd_set_param stdout 1
  procd_set_param stderr 1
  
  procd_close_instance
}

stop_service() {
  [ -f "$PIDFILE" ] && {
    local pid
    pid=$(cat "$PIDFILE" 2>/dev/null)
    [ -n "$pid" ] && kill "$pid" 2>/dev/null
    rm -f "$PIDFILE"
  }
}

reload_service() {
  stop
  start
}